development:
  adapter: postgresql
  encoding: unicode
  database: science_dev
  username: vgabou
  password:
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: science_test
  username: vgabou
  password:
  pool: 5
